var products = [
  {
    id: 1,
    name: "AirBuds Pro X",
    category: "Audio",
    price: 79,
    oldPrice: 129,
    icon: "🎧",
    badge: "sale",
    rating: 5,
  },
  {
    id: 2,
    name: "SmartWatch Ultra",
    category: "Wearables",
    price: 149,
    oldPrice: null,
    icon: "⌚",
    badge: "new",
    rating: 5,
  },
  {
    id: 3,
    name: "Mini Projector 4K",
    category: "Smart Home",
    price: 199,
    oldPrice: 249,
    icon: "📽️",
    badge: "hot",
    rating: 4,
  },
  {
    id: 4,
    name: "RGB Mechanical Keyboard",
    category: "Gaming",
    price: 89,
    oldPrice: null,
    icon: "⌨️",
    badge: "",
    rating: 5,
  },
  {
    id: 5,
    name: "USB-C Hub 7-in-1",
    category: "Accessories",
    price: 39,
    oldPrice: null,
    icon: "🔌",
    badge: "",
    rating: 4,
  },
  {
    id: 6,
    name: "Noise Cancel Headphones",
    category: "Audio",
    price: 119,
    oldPrice: 179,
    icon: "🎵",
    badge: "sale",
    rating: 5,
  },
  {
    id: 7,
    name: "Smart LED Strip 5m",
    category: "Smart Home",
    price: 29,
    oldPrice: null,
    icon: "💡",
    badge: "new",
    rating: 4,
  },
  {
    id: 8,
    name: "Fitness Band Pro",
    category: "Wearables",
    price: 59,
    oldPrice: null,
    icon: "🏃",
    badge: "",
    rating: 4,
  },
  {
    id: 9,
    name: "Portable Charger 20K",
    category: "Accessories",
    price: 45,
    oldPrice: null,
    icon: "🔋",
    badge: "",
    rating: 5,
  },
  {
    id: 10,
    name: "Gaming Controller",
    category: "Gaming",
    price: 69,
    oldPrice: 99,
    icon: "🎮",
    badge: "sale",
    rating: 5,
  },
  {
    id: 11,
    name: "Bluetooth Speaker 360",
    category: "Audio",
    price: 55,
    oldPrice: null,
    icon: "🔊",
    badge: "",
    rating: 4,
  },
  {
    id: 12,
    name: "Smart Plug 4-pack",
    category: "Smart Home",
    price: 34,
    oldPrice: null,
    icon: "🏠",
    badge: "new",
    rating: 4,
  },
  {
    id: 13,
    name: "Wireless Mouse Slim",
    category: "Accessories",
    price: 28,
    oldPrice: null,
    icon: "🖱️",
    badge: "",
    rating: 5,
  },
  {
    id: 14,
    name: "VR Headset Lite",
    category: "Gaming",
    price: 249,
    oldPrice: null,
    icon: "🥽",
    badge: "hot",
    rating: 4,
  },
  {
    id: 15,
    name: "Smart Ring Gen 2",
    category: "Wearables",
    price: 179,
    oldPrice: null,
    icon: "💍",
    badge: "new",
    rating: 5,
  },
  {
    id: 16,
    name: "True Wireless Earbuds",
    category: "Audio",
    price: 49,
    oldPrice: 79,
    icon: "🎶",
    badge: "sale",
    rating: 4,
  },
  {
    id: 17,
    name: "Webcam 4K HD",
    category: "Accessories",
    price: 85,
    oldPrice: null,
    icon: "📷",
    badge: "",
    rating: 5,
  },
  {
    id: 18,
    name: "Handheld Console",
    category: "Gaming",
    price: 139,
    oldPrice: null,
    icon: "👾",
    badge: "hot",
    rating: 5,
  },
];
